### ISSUE TITLE
Support for rewriting css files and inline styles

### ISSUE THREAD

**Issue by marcofranssen** [zqjimlove/hexo-cdnify#7]
Is it possible to add support for css files, so also fonts and images in css can be loaded from the cdn?

e.g.

```css
@font-face {
  font-family: 'Titillium Web';
  font-style: normal;
  font-weight: 600;
  src: local('Titillium WebSemiBold'), local('TitilliumWeb-SemiBold'), url(fonts/anMUvcNT0H1YN4FII8wpr46gJz9aNFrmnwBdd69aqzY.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
  font-display: swap;
}
```

Furthermore I also have some inline styles loading images.

```html
<span style="background-image:url(/images/6b7f0cf87fd84937834f07bb6719c0e521445911.png)" alt="Use the ACME DNS-Challenge to get a TLS certificate" class="thumbnail-image"></span>
```

**Comment by zqjimlove** [comment]
You can setup a mirroring CDN.A mirroring CDN doesn’t require you to upload anything to get started,And then it will loaded from CDN if the URL in css files is relative。

For example,
```css
@font-face {
  font-family: 'Titillium Web';
  font-style: normal;
  font-weight: 600;
  src: local('Titillium WebSemiBold'), local('TitilliumWeb-SemiBold'), url(fonts/anMUvcNT0H1YN4FII8wpr46gJz9aNFrmnwBdd69aqzY.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
  font-display: swap;
}
```
`url(fonts/anMUvcNT0H1YN4FII8wpr46gJz9aNFrmnwBdd69aqzY.woff2)` content of `https://cdn.example.com/style.css` , it will loaded fonts from `https://cdn.example.com/fonts/anMUvcNT0H1YN4FII8wpr46gJz9aNFrmnwBdd69aqzY.woff2`
